version: "3.9"
services:
  postgres:
    image: postgres:15.3-alpine
    env_file:
      - .env

    volumes:
      - pg_dev_data:/var/lib/postgresql/data # replace with on-system path
    ports:
      - "9291:5432" # for external access
#    hostname: postgres
#    user: "3000:1000"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lewdlocale" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_dev_data:
    driver: local